import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Scatterplot from '../components/scatterplot/Scatterplot'
import ScatterPoints from '../components/scatterpoints/ScatterPoints'
import LineGraph from '../components/linegraph/LineGraph'
import Axis from '../components/axis/Axis'
import TimeAxis from '../components/timeaxis/TimeAxis'
export default function Home() {




  const range = (start, stop, points) =>{
    const incr=(stop-start)/(points-1);
    let arr= Array.from({length: points}, (x, i) => i*incr)
    return arr;
  }
    

  let data_x2=range(0,2*3.141592654,25)
  let data_y2=data_x2.map(num=>Math.sin(num)+2)
  let data_y2new=data_x2.map(num=>Math.cos(num)+2)

  console.log({data_x2,data_y2})


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      {/* <Scatterplot
        data_x={data_x2}
        data_y={data_y2}
        chartWidth={900}
        chartHeight={600}
      /> */}

     
      <ScatterPoints data_x={data_x2} data_y={data_y2new} chartWidth={1500} chartHeight={600} color="red">
      <ScatterPoints data_x={data_x2} data_y={data_y2} chartWidth={1500} chartHeight={600} color="black">
      <LineGraph data_x={data_x2} data_y={data_y2new} chartWidth={1500} chartHeight={600} color="blue">
          <TimeAxis data_x={data_x2} data_y={data_y2} chartWidth={1500} chartHeight={600}>
                <div id="scatter2"/>
          </TimeAxis>
      </LineGraph>
      </ScatterPoints>
      </ScatterPoints>
    
      


    </div>
  )
}

